apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: argo
  labels:
    app: vllm
spec:
  type: NodePort
  selector:
    app: vllm
  ports:
    - protocol: TCP
      port: 80 # Kubernetes サービスが公開するポート
      targetPort: 8000 # Pod のコンテナポート
      nodePort: 30201 # NodePort のポート番号
