apiVersion: v1
kind: Pod
metadata:
  name: gvisor-cilium-test
  labels:
    app: sandbox-test
spec:
  runtimeClassName: gvisor
  containers:
  - name: tester
    image: curlimages/curl:latest
    command: ["sh", "-c", "curl -s --head --connect-timeout 5 https://google.com && sleep 3600"]