apiVersion: v1 
kind: Service 
metadata: 
  name: hello-service 
  namespace: default
spec: 
  selector: 
    app: hello 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 8080 
    nodePort: 30200 
  type: NodePort