apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
  labels:
    app.kubernetes.io/name: webhook-sensor
    app.kubernetes.io/component: sensor
    app.kubernetes.io/part-of: argo-events
  annotations:
    description: "Detects 'performance' event and triggers a hello-world workflow"
spec:
  template:
    serviceAccountName: workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: performance
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                entrypoint: hello-world
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by event payload from test-dep
                    value: hello world
                templates:
                - name: hello-world
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: busybox
                    command: [echo]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: test-dep
                # リクエストボディ(JSON)の中から、'message'フィールドの値を抽出します
                dataKey: body.message
              dest: spec.arguments.parameters.0.value
