apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 8080
        targetPort: 8080
    metadata:
      labels:
        app.kubernetes.io/name: webhook-eventsource
        app.kubernetes.io/component: eventsource
        app.kubernetes.io/part-of: argo-events
      annotations:
        description: "Receives performance and accuracy events for ML model evaluation"
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    performance:
      port: "8080"
      endpoint: /performance
      method: POST
    #accuracy:
    #  port: "8080"
    #  endpoint: /accuracy
    #  method: POST

#    example-foo:
#      port: "12000"
#      endpoint: /example2
#      method: POST

# Uncomment to use secure webhook
#    example-secure:
#      port: "13000"
#      endpoint: "/secure"
#      method: "POST"
#      # k8s secret that contains the cert
#      serverCertSecret:
#        name: my-secret
#        key: cert-key
#      # k8s secret that contains the private key
#      serverKeySecret:
#        name: my-secret
#        key: pk-key
