apiVersion: v1
kind: Service
metadata:
  name: hf-transformers-service
  labels:
    app: hf-transformers
spec:
  type: NodePort
  selector:
    app: hf-transformers
  ports:
    - protocol: TCP
      port: 80 # Kubernetes サービスが公開するポート
      targetPort: 8000 # Pod のコンテナポート
      nodePort: 30200 # NodePort のポート番号
