apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-dashboard
  template:
    metadata:
      labels:
        app: monitor-dashboard
    spec:
      #hostNetwork: true
      containers:
        - name: influxdb
          image: influxdb:1.8
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
          env:
            - name: INFLUXDB_DB
              value: llmbench
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          volumeMounts:
           - name: grafana-data
             mountPath: /var/lib/grafana
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
        - name: gpumonitor
          image: wellflat/gpumonitor:latest
          env:
            - name: INFLUXDB_HOST
              value: localhost
            - name: INFLUXDB_PORT
              value: "8086"
            - name: INFLUXDB_DBNAME
              value: llmbench
            - name: WAIT_TIME
              value: "5"
            - name: NVIDIA_VISIBLE_DEVICES
              value: all
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: all
          volumeMounts:
            - name: monitor-data
              mountPath: /workspace/metrics
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: monitor-data
          persistentVolumeClaim:
            claimName: monitor-data-pvc