apiVersion: v1
kind: PersistentVolume
metadata:
  name: vllm-hf-cache-pv
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vllm-local
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - gpu-03
  hostPath:
    path: /var/lib/llm-d/vllm-hf-cache
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-hf-cache
  namespace: llm-d-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: vllm-local
  volumeName: vllm-hf-cache-pv
