apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      containers:
        - name: comfyui
          image: wellflat/comfyui:0.3.29
          ports:
            - containerPort: 8188 # ComfyUI のデフォルトポート
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: comfyui-model
              mountPath: /workspace/ComfyUI/models
      volumes:
        - name: comfyui-model
          persistentVolumeClaim:
            claimName: comfyui-model-pvc # PersistentVolumeClaim を使用する場合