---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-model-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /var/tmp/comfyui/models
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-model-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: comfyui-model-pv

# temporary storage for ComfyUI
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-tmp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/tmp/comfyui/tmp
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-tmp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: comfyui-tmp-pv