apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-data-pv
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    #path: /home/gmaasadmin/.cache/huggingface/hub
    path: /mnt/lustre/cache/huggingface/hub
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Ti
  storageClassName: ""
  volumeName: hf-data-pv
---
