---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-bench-model-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /minikube-host/.cache/huggingface/hub
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-bench-model-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  reclaimPolicy: Retain
  volumeName: llm-bench-model-pv