services:
  app:
    container_name: comfyui
    image: comfyui:0.3.29
    build:
      context: .
      dockerfile: Dockerfile
    #image: nvcr.io/nvidia/pytorch:24.10-py3
    volumes:
      - type: bind
        source: ./ComfyUI/models
        target: /workspace/ComfyUI/models
      #- ./input:/ComfyUI/input
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
    #command: ["sleep", "infinity"] # debug用コンテナが終了しないようにする
    ports:
      # host:container
      - "8188:8188"
    networks:
      comfyui-network:
        aliases:
          - comfyui  # コンテナのホスト名
networks:
  comfyui-network:
