apiVersion: v1
kind: Service
metadata:
  name: minio-hl-service
  namespace: argo
  labels:
    app: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000 # Kubernetes サービスが公開するポート
      targetPort: 9000 # Pod のコンテナポート (minio-hl)
      nodePort: 30900 # NodePort のポート番号