apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-workflows
    meta.helm.sh/release-namespace: default
    workflows.argoproj.io/default-artifact-repository: s3-artifacts-repository
  creationTimestamp: "2025-09-07T07:19:07Z"
  labels:
    app: workflow-controller
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo-workflows
    helm.sh/chart: argo-workflows-0.45.23
  name: argo-workflows-workflow-controller-configmap
  namespace: default
  resourceVersion: "1658048"
  uid: 654d91c2-ba56-4e9d-971d-8dcae4f059f3
data:
  config: |
    nodeEvents:
      enabled: true
    workflowEvents:
      enabled: true
    artifactRepository:
      s3:
        endpoint: s3.amazonaws.com
        bucket: elements-benchmark-artifacts-dev
        insecure: false
        accessKeySecret:
          name: aws-access-key
          key: accessKey
        secretKeySecret:
          name: aws-access-key
          key: secretAccessKey
