# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  artifactRepository: |
    archiveLogs: true
    s3: 
      bucket: argo-artifacts
      endpoint: play.min.io
      insecure: false
      accessKeySecret:
       name: play-minio-argo-credentials
       key: accessKey
      secretKeySecret:
       name: play-minio-argo-credentials
       key: secretKey
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"workflow-controller-configmap","namespace":"argo"}}
  creationTimestamp: "2025-07-19T14:54:58Z"
  name: workflow-controller-configmap
  namespace: argo
  resourceVersion: "3126577"
  uid: 41f13512-e651-4548-b391-18f6b7d22fc6
