apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: performance-workflow-template
spec:
  serviceAccountName: workflow-sa # Apply to all templates in this workflow
  entrypoint: benchmark-lifecycle
  templates:
    - name: benchmark-lifecycle
      dag:
        tasks:
          - name: hf-dataset-loader
            template: hf-dataset-loader-template
            arguments:
              parameters:
                - name: dataset-id
                  value: "{{workflow.parameters.dataset-id}}"
          - name: genai-perf-sweep
            template: genai-perf-profile-template
            dependencies: [hf-dataset-loader]
            arguments:
              parameters:
                - name: model-id
                  value: "{{workflow.parameters.model-id}}"
                - name: output_token_mean
                  value: "{{item.output_token_mean}}"
                - name: request_count
                  value: "{{workflow.parameters.request_count}}"
                - name: artifact_suffix
                  value: "{{item.artifact_suffix}}"
            withParam: >
              [
                {"output_token_mean": "100", "artifact_suffix": "token100"},
                {"output_token_mean": "200", "artifact_suffix": "token200"},
                {"output_token_mean": "400", "artifact_suffix": "token400"}
              ]
          - name: collect-artifacts
            template: collect-artifacts-template
            dependencies: [genai-perf-sweep]
    
    - name: hf-dataset-loader-template
      inputs:
        parameters:
          - name: dataset-id
      container:
        image: wellflat/hf-dataloader:latest
        volumeMounts:
          - name: hf-data
            mountPath: /root/.cache/huggingface/hub
        env:
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: hf_token
          - name: HF_HUB_ENABLE_TRANSFER
            value: "1"
        args: # huggingface-cli の引数
          - "download"
          - "--repo-type"
          - "dataset"
          - "{{inputs.parameters.dataset-id}}"
      volumes:
        - name: hf-data
          persistentVolumeClaim:
            claimName: hf-data-pvc
    
    - name: genai-perf-profile-template
      inputs:
        parameters:
          - name: model-id
          - name: output_token_mean
          - name: request_count
          - name: artifact_suffix
      container:
        image: nvcr.io/nvidia/tritonserver:25.07-py3-sdk
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
          - name: hf-data
            mountPath: /root/.cache/huggingface/hub
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
          - name: ARTIFACT_BASE_DIR
            value: /root/.cache/huggingface/hub/benchmark_results/genai-perf
        command: ["/bin/bash", "-c"]
        args:
          - |
           genai-perf profile -m {{inputs.parameters.model-id}} \
           --endpoint-type chat \
           --synthetic-input-tokens-mean 150 \
           --synthetic-input-tokens-stddev 30 \
           --output-tokens-mean {{inputs.parameters.output_token_mean}} \
           --output-tokens-stddev 30 \
           --num-prompts 200 \
           --concurrency 1 \
           --random-seed 42 \
           --streaming \
           --request-count {{inputs.parameters.request_count}} \
           --warmup-request-count 10 \
           --url http://vllm-service:80 \
           --server-metrics-url http://dcgm-exporter.prometheus.svc.cluster.local:9400/metrics \
           --artifact-dir ${ARTIFACT_BASE_DIR}/{{workflow.uid}}/{{inputs.parameters.model-id}}/{{inputs.parameters.artifact_suffix}} \
           --verbose
      outputs:
        artifacts:
          - name: benchmark-results
            # This path MUST match the --artifact-dir used in the genai-perf command above.
            path: /root/.cache/huggingface/hub/benchmark_results/genai-perf/{{workflow.uid}}/{{inputs.parameters.model-id}}/{{inputs.parameters.artifact_suffix}}
            archive:
              none: { }
      volumes:
        - name: hf-data
          persistentVolumeClaim:
            claimName: hf-data-pvc

    - name: collect-artifacts-template
      #inputs:
      #  artifacts:
        # This will be a collection of all artifacts generated by the parallel genai-perf-sweep steps.
      #    - name: benchmark-results
      #      path: /tmp/results # The artifacts will be placed in this directory
      container:
        image: wellflat/hf-dataloader:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "--- Collected benchmark artifacts are available ---"
            ls -R /root/.cache/huggingface/hub/benchmark_results/genai-perf
            echo "--- End of artifact list ---"
            # You can add commands here to upload the results to a repository.
            # e.g., huggingface-cli upload my-benchmark-results-repo /tmp/results --repo-type dataset
        volumeMounts:
          - name: hf-data
            mountPath: /root/.cache/huggingface/hub
        env:
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: hf_token
      volumes:
        - name: hf-data
          persistentVolumeClaim:
            claimName: hf-data-pvc