apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-bench-model-argo-pvc
  namespace: argo
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: llm-bench-model-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi