apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sft-train-workflow-template
spec:
  arguments:
    parameters:
      - name: model-id
        value: "openai/gpt-oss-20b" # デフォルトのモデルID
      - name: dataset-id
        value: "HuggingFaceH4/Multilingual-Thinking" # デフォルトのデータセットID

  entrypoint: train-lifecycle

  volumes:
    - name: hf-data
      persistentVolumeClaim:
        claimName: hf-data-pvc

  templates:
    - name: train-lifecycle
      dag:
        tasks:
          - name: hf-dataset-loader
            template: hf-dataset-loader
            arguments:
              parameters:
                - name: dataset-id
                  value: "{{workflow.parameters.dataset-id}}"
          - name: sft-train-job
            template: sft-train-job
            dependencies: [hf-dataset-loader]
            arguments:
              parameters:
                - name: model-id
                  value: "{{workflow.parameters.model-id}}"
    
    - name: hf-dataset-loader
      inputs:
        parameters:
          - name: dataset-id
      container:
        image: wellflat/hf-dataloader:latest
        volumeMounts:
          - name: hf-data
            mountPath: /root/.cache/huggingface/hub
        env:
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: hf_token
          - name: HF_HUB_ENABLE_TRANSFER
            value: "1"
          - name: DATASET_ID
            value: "{{inputs.parameters.dataset-id}}"
        args: # huggingface-cli の引数
          - "download"
          - "--repo-type"
          - "dataset"
          - "$(DATASET_ID)"
      volumes:
        - name: hf-data
          persistentVolumeClaim:
            claimName: hf-data-pvc
    
    - name: sft-train-job
      inputs:
        parameters:
          - name: model-id
      container:
        image: wellflat/llm-trl-train:latest
        resources:
          limits:
            nvidia.com/gpu: 8
          requests:
            nvidia.com/gpu: 8
        volumeMounts:
          - name: hf-data
            mountPath: /root/.cache/huggingface/hub
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: all
          - name: MODEL_ID
            value: "{{inputs.parameters.model-id}}"
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: hf_token
        command: ["python", "train.py"]
